// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/rag/rag_service.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 解析文档请求
type ParseDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentRequest) Reset() {
	*x = ParseDocumentRequest{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentRequest) ProtoMessage() {}

func (x *ParseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentRequest.ProtoReflect.Descriptor instead.
func (*ParseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *ParseDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ParseDocumentRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ParseDocumentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ParseDocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// 解析文档响应
type ParseDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentResponse) Reset() {
	*x = ParseDocumentResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentResponse) ProtoMessage() {}

func (x *ParseDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentResponse.ProtoReflect.Descriptor instead.
func (*ParseDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *ParseDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseDocumentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseDocumentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 向量化文档请求
type VectorizeDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	KnowledgeBaseId string                 `protobuf:"bytes,3,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	CollectionName  string                 `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ObjectKey       string                 `protobuf:"bytes,6,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VectorizeDocumentRequest) Reset() {
	*x = VectorizeDocumentRequest{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeDocumentRequest) ProtoMessage() {}

func (x *VectorizeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeDocumentRequest.ProtoReflect.Descriptor instead.
func (*VectorizeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *VectorizeDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// 向量化文档响应
type VectorizeDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeDocumentResponse) Reset() {
	*x = VectorizeDocumentResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeDocumentResponse) ProtoMessage() {}

func (x *VectorizeDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeDocumentResponse.ProtoReflect.Descriptor instead.
func (*VectorizeDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *VectorizeDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VectorizeDocumentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 删除文档向量请求
type DeleteDocumentVectorsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentIds    []string               `protobuf:"bytes,1,rep,name=document_ids,json=documentIds,proto3" json:"document_ids,omitempty"`
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteDocumentVectorsRequest) Reset() {
	*x = DeleteDocumentVectorsRequest{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentVectorsRequest) ProtoMessage() {}

func (x *DeleteDocumentVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentVectorsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentVectorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDocumentVectorsRequest) GetDocumentIds() []string {
	if x != nil {
		return x.DocumentIds
	}
	return nil
}

func (x *DeleteDocumentVectorsRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

// 删除文档向量响应
type DeleteDocumentVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentVectorsResponse) Reset() {
	*x = DeleteDocumentVectorsResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentVectorsResponse) ProtoMessage() {}

func (x *DeleteDocumentVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentVectorsResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentVectorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentVectorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocumentVectorsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteDocumentVectorsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 对话请求
type ChatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UseRag              bool                   `protobuf:"varint,2,opt,name=use_rag,json=useRag,proto3" json:"use_rag,omitempty"`
	KnowledgeBaseIds    []string               `protobuf:"bytes,3,rep,name=knowledge_base_ids,json=knowledgeBaseIds,proto3" json:"knowledge_base_ids,omitempty"`
	TopK                int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,5,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	SimilarityWeight    float32                `protobuf:"fixed32,6,opt,name=similarity_weight,json=similarityWeight,proto3" json:"similarity_weight,omitempty"`
	History             []*ChatMessage         `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetUseRag() bool {
	if x != nil {
		return x.UseRag
	}
	return false
}

func (x *ChatRequest) GetKnowledgeBaseIds() []string {
	if x != nil {
		return x.KnowledgeBaseIds
	}
	return nil
}

func (x *ChatRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ChatRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *ChatRequest) GetSimilarityWeight() float32 {
	if x != nil {
		return x.SimilarityWeight
	}
	return 0
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

// 对话消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, system
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 对话响应
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Sources       []*RAGSource           `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetSources() []*RAGSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

// 流式对话响应
type ChatStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // start, content, sources, done
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Sources       []*RAGSource           `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{9}
}

func (x *ChatStreamResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatStreamResponse) GetSources() []*RAGSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatStreamResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

// RAG 来源
type RAGSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGSource) Reset() {
	*x = RAGSource{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSource) ProtoMessage() {}

func (x *RAGSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSource.ProtoReflect.Descriptor instead.
func (*RAGSource) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{10}
}

func (x *RAGSource) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RAGSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RAGSource) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RAGSource) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

// 检索文档请求
type RetrieveDocumentsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	KnowledgeBaseIds    []string               `protobuf:"bytes,2,rep,name=knowledge_base_ids,json=knowledgeBaseIds,proto3" json:"knowledge_base_ids,omitempty"`
	TopK                int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,4,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetrieveDocumentsRequest) Reset() {
	*x = RetrieveDocumentsRequest{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDocumentsRequest) ProtoMessage() {}

func (x *RetrieveDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDocumentsRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveDocumentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveDocumentsRequest) GetKnowledgeBaseIds() []string {
	if x != nil {
		return x.KnowledgeBaseIds
	}
	return nil
}

func (x *RetrieveDocumentsRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveDocumentsRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

// 检索文档响应
type RetrieveDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*RAGSource           `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveDocumentsResponse) Reset() {
	*x = RetrieveDocumentsResponse{}
	mi := &file_proto_rag_rag_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDocumentsResponse) ProtoMessage() {}

func (x *RetrieveDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rag_rag_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDocumentsResponse.ProtoReflect.Descriptor instead.
func (*RetrieveDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rag_rag_service_proto_rawDescGZIP(), []int{12}
}

func (x *RetrieveDocumentsResponse) GetDocuments() []*RAGSource {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_proto_rag_rag_service_proto protoreflect.FileDescriptor

const file_proto_rag_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/rag/rag_service.proto\x12\x03rag\"\x96\x01\n" +
	"\x14ParseDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\"p\n" +
	"\x15ParseDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xdf\x01\n" +
	"\x18VectorizeDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12*\n" +
	"\x11knowledge_base_id\x18\x03 \x01(\tR\x0fknowledgeBaseId\x12'\n" +
	"\x0fcollection_name\x18\x04 \x01(\tR\x0ecollectionName\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"object_key\x18\x06 \x01(\tR\tobjectKey\"Z\n" +
	"\x19VectorizeDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"j\n" +
	"\x1cDeleteDocumentVectorsRequest\x12!\n" +
	"\fdocument_ids\x18\x01 \x03(\tR\vdocumentIds\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\"\x83\x01\n" +
	"\x1dDeleteDocumentVectorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8b\x02\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\ause_rag\x18\x02 \x01(\bR\x06useRag\x12,\n" +
	"\x12knowledge_base_ids\x18\x03 \x03(\tR\x10knowledgeBaseIds\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x121\n" +
	"\x14similarity_threshold\x18\x05 \x01(\x02R\x13similarityThreshold\x12+\n" +
	"\x11similarity_weight\x18\x06 \x01(\x02R\x10similarityWeight\x12*\n" +
	"\ahistory\x18\a \x03(\v2\x10.rag.ChatMessageR\ahistory\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"s\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12(\n" +
	"\asources\x18\x02 \x03(\v2\x0e.rag.RAGSourceR\asources\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x05R\n" +
	"tokensUsed\"\x89\x01\n" +
	"\x12ChatStreamResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12(\n" +
	"\asources\x18\x03 \x03(\v2\x0e.rag.RAGSourceR\asources\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\"r\n" +
	"\tRAGSource\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\"\xa6\x01\n" +
	"\x18RetrieveDocumentsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x12knowledge_base_ids\x18\x02 \x03(\tR\x10knowledgeBaseIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x121\n" +
	"\x14similarity_threshold\x18\x04 \x01(\x02R\x13similarityThreshold\"I\n" +
	"\x19RetrieveDocumentsResponse\x12,\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0e.rag.RAGSourceR\tdocuments2\xc4\x03\n" +
	"\n" +
	"RAGService\x12F\n" +
	"\rParseDocument\x12\x19.rag.ParseDocumentRequest\x1a\x1a.rag.ParseDocumentResponse\x12R\n" +
	"\x11VectorizeDocument\x12\x1d.rag.VectorizeDocumentRequest\x1a\x1e.rag.VectorizeDocumentResponse\x12^\n" +
	"\x15DeleteDocumentVectors\x12!.rag.DeleteDocumentVectorsRequest\x1a\".rag.DeleteDocumentVectorsResponse\x12+\n" +
	"\x04Chat\x12\x10.rag.ChatRequest\x1a\x11.rag.ChatResponse\x129\n" +
	"\n" +
	"ChatStream\x12\x10.rag.ChatRequest\x1a\x17.rag.ChatStreamResponse0\x01\x12R\n" +
	"\x11RetrieveDocuments\x12\x1d.rag.RetrieveDocumentsRequest\x1a\x1e.rag.RetrieveDocumentsResponseB\x12Z\x10ragljx/proto/ragb\x06proto3"

var (
	file_proto_rag_rag_service_proto_rawDescOnce sync.Once
	file_proto_rag_rag_service_proto_rawDescData []byte
)

func file_proto_rag_rag_service_proto_rawDescGZIP() []byte {
	file_proto_rag_rag_service_proto_rawDescOnce.Do(func() {
		file_proto_rag_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rag_rag_service_proto_rawDesc), len(file_proto_rag_rag_service_proto_rawDesc)))
	})
	return file_proto_rag_rag_service_proto_rawDescData
}

var file_proto_rag_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_rag_rag_service_proto_goTypes = []any{
	(*ParseDocumentRequest)(nil),          // 0: rag.ParseDocumentRequest
	(*ParseDocumentResponse)(nil),         // 1: rag.ParseDocumentResponse
	(*VectorizeDocumentRequest)(nil),      // 2: rag.VectorizeDocumentRequest
	(*VectorizeDocumentResponse)(nil),     // 3: rag.VectorizeDocumentResponse
	(*DeleteDocumentVectorsRequest)(nil),  // 4: rag.DeleteDocumentVectorsRequest
	(*DeleteDocumentVectorsResponse)(nil), // 5: rag.DeleteDocumentVectorsResponse
	(*ChatRequest)(nil),                   // 6: rag.ChatRequest
	(*ChatMessage)(nil),                   // 7: rag.ChatMessage
	(*ChatResponse)(nil),                  // 8: rag.ChatResponse
	(*ChatStreamResponse)(nil),            // 9: rag.ChatStreamResponse
	(*RAGSource)(nil),                     // 10: rag.RAGSource
	(*RetrieveDocumentsRequest)(nil),      // 11: rag.RetrieveDocumentsRequest
	(*RetrieveDocumentsResponse)(nil),     // 12: rag.RetrieveDocumentsResponse
}
var file_proto_rag_rag_service_proto_depIdxs = []int32{
	7,  // 0: rag.ChatRequest.history:type_name -> rag.ChatMessage
	10, // 1: rag.ChatResponse.sources:type_name -> rag.RAGSource
	10, // 2: rag.ChatStreamResponse.sources:type_name -> rag.RAGSource
	10, // 3: rag.RetrieveDocumentsResponse.documents:type_name -> rag.RAGSource
	0,  // 4: rag.RAGService.ParseDocument:input_type -> rag.ParseDocumentRequest
	2,  // 5: rag.RAGService.VectorizeDocument:input_type -> rag.VectorizeDocumentRequest
	4,  // 6: rag.RAGService.DeleteDocumentVectors:input_type -> rag.DeleteDocumentVectorsRequest
	6,  // 7: rag.RAGService.Chat:input_type -> rag.ChatRequest
	6,  // 8: rag.RAGService.ChatStream:input_type -> rag.ChatRequest
	11, // 9: rag.RAGService.RetrieveDocuments:input_type -> rag.RetrieveDocumentsRequest
	1,  // 10: rag.RAGService.ParseDocument:output_type -> rag.ParseDocumentResponse
	3,  // 11: rag.RAGService.VectorizeDocument:output_type -> rag.VectorizeDocumentResponse
	5,  // 12: rag.RAGService.DeleteDocumentVectors:output_type -> rag.DeleteDocumentVectorsResponse
	8,  // 13: rag.RAGService.Chat:output_type -> rag.ChatResponse
	9,  // 14: rag.RAGService.ChatStream:output_type -> rag.ChatStreamResponse
	12, // 15: rag.RAGService.RetrieveDocuments:output_type -> rag.RetrieveDocumentsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_rag_rag_service_proto_init() }
func file_proto_rag_rag_service_proto_init() {
	if File_proto_rag_rag_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rag_rag_service_proto_rawDesc), len(file_proto_rag_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rag_rag_service_proto_goTypes,
		DependencyIndexes: file_proto_rag_rag_service_proto_depIdxs,
		MessageInfos:      file_proto_rag_rag_service_proto_msgTypes,
	}.Build()
	File_proto_rag_rag_service_proto = out.File
	file_proto_rag_rag_service_proto_goTypes = nil
	file_proto_rag_rag_service_proto_depIdxs = nil
}
