// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/rag/rag_service.proto

package rag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAGService_ParseDocument_FullMethodName         = "/rag.RAGService/ParseDocument"
	RAGService_VectorizeDocument_FullMethodName     = "/rag.RAGService/VectorizeDocument"
	RAGService_DeleteDocumentVectors_FullMethodName = "/rag.RAGService/DeleteDocumentVectors"
	RAGService_DeleteCollection_FullMethodName      = "/rag.RAGService/DeleteCollection"
	RAGService_Chat_FullMethodName                  = "/rag.RAGService/Chat"
	RAGService_ChatStream_FullMethodName            = "/rag.RAGService/ChatStream"
	RAGService_RetrieveDocuments_FullMethodName     = "/rag.RAGService/RetrieveDocuments"
)

// RAGServiceClient is the client API for RAGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RAG 服务定义
type RAGServiceClient interface {
	// 解析文档
	ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error)
	// 向量化文档
	VectorizeDocument(ctx context.Context, in *VectorizeDocumentRequest, opts ...grpc.CallOption) (*VectorizeDocumentResponse, error)
	// 删除文档向量
	DeleteDocumentVectors(ctx context.Context, in *DeleteDocumentVectorsRequest, opts ...grpc.CallOption) (*DeleteDocumentVectorsResponse, error)
	// 删除集合
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error)
	// RAG 对话
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// RAG 对话（流式）
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error)
	// 检索相关文档
	RetrieveDocuments(ctx context.Context, in *RetrieveDocumentsRequest, opts ...grpc.CallOption) (*RetrieveDocumentsResponse, error)
}

type rAGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAGServiceClient(cc grpc.ClientConnInterface) RAGServiceClient {
	return &rAGServiceClient{cc}
}

func (c *rAGServiceClient) ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDocumentResponse)
	err := c.cc.Invoke(ctx, RAGService_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) VectorizeDocument(ctx context.Context, in *VectorizeDocumentRequest, opts ...grpc.CallOption) (*VectorizeDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorizeDocumentResponse)
	err := c.cc.Invoke(ctx, RAGService_VectorizeDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) DeleteDocumentVectors(ctx context.Context, in *DeleteDocumentVectorsRequest, opts ...grpc.CallOption) (*DeleteDocumentVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentVectorsResponse)
	err := c.cc.Invoke(ctx, RAGService_DeleteDocumentVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCollectionResponse)
	err := c.cc.Invoke(ctx, RAGService_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, RAGService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RAGService_ServiceDesc.Streams[0], RAGService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RAGService_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamResponse]

func (c *rAGServiceClient) RetrieveDocuments(ctx context.Context, in *RetrieveDocumentsRequest, opts ...grpc.CallOption) (*RetrieveDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveDocumentsResponse)
	err := c.cc.Invoke(ctx, RAGService_RetrieveDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAGServiceServer is the server API for RAGService service.
// All implementations must embed UnimplementedRAGServiceServer
// for forward compatibility.
//
// RAG 服务定义
type RAGServiceServer interface {
	// 解析文档
	ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error)
	// 向量化文档
	VectorizeDocument(context.Context, *VectorizeDocumentRequest) (*VectorizeDocumentResponse, error)
	// 删除文档向量
	DeleteDocumentVectors(context.Context, *DeleteDocumentVectorsRequest) (*DeleteDocumentVectorsResponse, error)
	// 删除集合
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	// RAG 对话
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// RAG 对话（流式）
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error
	// 检索相关文档
	RetrieveDocuments(context.Context, *RetrieveDocumentsRequest) (*RetrieveDocumentsResponse, error)
	mustEmbedUnimplementedRAGServiceServer()
}

// UnimplementedRAGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAGServiceServer struct{}

func (UnimplementedRAGServiceServer) ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedRAGServiceServer) VectorizeDocument(context.Context, *VectorizeDocumentRequest) (*VectorizeDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorizeDocument not implemented")
}
func (UnimplementedRAGServiceServer) DeleteDocumentVectors(context.Context, *DeleteDocumentVectorsRequest) (*DeleteDocumentVectorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocumentVectors not implemented")
}
func (UnimplementedRAGServiceServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedRAGServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedRAGServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedRAGServiceServer) RetrieveDocuments(context.Context, *RetrieveDocumentsRequest) (*RetrieveDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveDocuments not implemented")
}
func (UnimplementedRAGServiceServer) mustEmbedUnimplementedRAGServiceServer() {}
func (UnimplementedRAGServiceServer) testEmbeddedByValue()                    {}

// UnsafeRAGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAGServiceServer will
// result in compilation errors.
type UnsafeRAGServiceServer interface {
	mustEmbedUnimplementedRAGServiceServer()
}

func RegisterRAGServiceServer(s grpc.ServiceRegistrar, srv RAGServiceServer) {
	// If the following call pancis, it indicates UnimplementedRAGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAGService_ServiceDesc, srv)
}

func _RAGService_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).ParseDocument(ctx, req.(*ParseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_VectorizeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorizeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).VectorizeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_VectorizeDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).VectorizeDocument(ctx, req.(*VectorizeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_DeleteDocumentVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).DeleteDocumentVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_DeleteDocumentVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).DeleteDocumentVectors(ctx, req.(*DeleteDocumentVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RAGServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RAGService_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamResponse]

func _RAGService_RetrieveDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).RetrieveDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_RetrieveDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).RetrieveDocuments(ctx, req.(*RetrieveDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RAGService_ServiceDesc is the grpc.ServiceDesc for RAGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.RAGService",
	HandlerType: (*RAGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _RAGService_ParseDocument_Handler,
		},
		{
			MethodName: "VectorizeDocument",
			Handler:    _RAGService_VectorizeDocument_Handler,
		},
		{
			MethodName: "DeleteDocumentVectors",
			Handler:    _RAGService_DeleteDocumentVectors_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _RAGService_DeleteCollection_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _RAGService_Chat_Handler,
		},
		{
			MethodName: "RetrieveDocuments",
			Handler:    _RAGService_RetrieveDocuments_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _RAGService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rag/rag_service.proto",
}
