# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import rag_service_pb2 as app_dot_proto_dot_rag__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/proto/rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub(object):
    """RAG 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/rag.RAGService/ParseDocument',
                request_serializer=app_dot_proto_dot_rag__service__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.ParseDocumentResponse.FromString,
                _registered_method=True)
        self.VectorizeDocument = channel.unary_unary(
                '/rag.RAGService/VectorizeDocument',
                request_serializer=app_dot_proto_dot_rag__service__pb2.VectorizeDocumentRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.VectorizeDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocumentVectors = channel.unary_unary(
                '/rag.RAGService/DeleteDocumentVectors',
                request_serializer=app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/rag.RAGService/Chat',
                request_serializer=app_dot_proto_dot_rag__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/rag.RAGService/ChatStream',
                request_serializer=app_dot_proto_dot_rag__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.ChatStreamResponse.FromString,
                _registered_method=True)
        self.RetrieveDocuments = channel.unary_unary(
                '/rag.RAGService/RetrieveDocuments',
                request_serializer=app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """RAG 服务定义
    """

    def ParseDocument(self, request, context):
        """解析文档
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorizeDocument(self, request, context):
        """向量化文档
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocumentVectors(self, request, context):
        """删除文档向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """RAG 对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """RAG 对话（流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveDocuments(self, request, context):
        """检索相关文档
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.ParseDocumentRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.ParseDocumentResponse.SerializeToString,
            ),
            'VectorizeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorizeDocument,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.VectorizeDocumentRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.VectorizeDocumentResponse.SerializeToString,
            ),
            'DeleteDocumentVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocumentVectors,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.ChatStreamResponse.SerializeToString,
            ),
            'RetrieveDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveDocuments,
                    request_deserializer=app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsRequest.FromString,
                    response_serializer=app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """RAG 服务定义
    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/ParseDocument',
            app_dot_proto_dot_rag__service__pb2.ParseDocumentRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.ParseDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorizeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/VectorizeDocument',
            app_dot_proto_dot_rag__service__pb2.VectorizeDocumentRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.VectorizeDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocumentVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/DeleteDocumentVectors',
            app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.DeleteDocumentVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Chat',
            app_dot_proto_dot_rag__service__pb2.ChatRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.RAGService/ChatStream',
            app_dot_proto_dot_rag__service__pb2.ChatRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/RetrieveDocuments',
            app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsRequest.SerializeToString,
            app_dot_proto_dot_rag__service__pb2.RetrieveDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
